# Generated by Django 6.0.6 on 2026-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True, verbose_name="解析"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="是否正確"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="題目內容"),
        ),
    ]
