# Generated by Django 6.0.6 on 2026-06-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_explanation_alter_choice_is_correct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions_requested', models.IntegerField(default=5, verbose_name='設定測驗題數')),
                ('current_index', models.IntegerField(default=0, verbose_name='目前進行到第幾題')),
                ('score', models.IntegerField(default=0, verbose_name='目前得分')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成測驗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='測驗時間')),
                ('time_remaining', models.IntegerField(default=600, verbose_name='剩餘時間(秒)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='測驗學生')),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='出題順序')),
                ('is_answered', models.BooleanField(default=False, verbose_name='是否已作答')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否答對')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quiz.quizsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
